using System.Globalization;
using System.IO;

namespace FAIC.Types
{
    public struct FrameCollection
    {
        public struct Frame
        {
            public string Path;
            public decimal Time;
            public readonly void Write(StreamWriter writer, decimal previousTime)
            {
                writer.WriteLine($"file \'{Path}\'");
                writer.WriteLine($"duration {Time - previousTime}");
            }
        }

        public double Length;
        public double AverageFrameRate;
        public double RFrameRate;

        private const string FPS_TAG = "fps";
        private const decimal DEFAULT_FRAME_LENGTH = 1 / 25;
        public List<string> stream;
        public decimal averageFrameRate;
        public readonly void ToConcat(StreamWriter writer)
        {
            writer.WriteLine("ffconcat version 1.0"); //must come first
            writer.WriteLine("#Generated by Fast Animated Image Converter");
            writer.WriteLine("#https://github.com/JaimeShirazi/FastAnimatedImageConverter");
            writer.WriteLine("#Unsupported ffconcat syntax will be ignored by Fast Animated Image Converter.");
            decimal time = 0;
            for (int i = 0; i < stream.Count; i++)
            {
                writer.WriteLine($"file \'{stream[i]}\'");
                decimal nextTime = (i + 1) / averageFrameRate;
                writer.WriteLine($"duration {nextTime - time}");
                time = nextTime;
            }
        }
        public FrameCollection(string filePath)
        {
            if (!Path.Exists(filePath)) return;
            using (StreamReader sr = new StreamReader(filePath))
            {
                stream = new List<Frame>();
                decimal time = 0;
                Frame nextFrame = default;

                while (!sr.EndOfStream)
                {
                    var s = sr.ReadLine();
                    if (s == null) continue;

                    if (s.StartsWith("file "))
                    {
                        if (!string.IsNullOrEmpty(nextFrame.Path))
                        {
                            nextFrame.Time = stream.Count > 0 ? stream[^1].Time : DEFAULT_FRAME_LENGTH;
                            stream.Add(nextFrame);
                            nextFrame = new();
                        }
                        nextFrame.Path =
                        }
                    else if (s.StartsWith("duration "))
                    {
                        if (decimal.TryParse(s[9..], NumberStyles.Number, CultureInfo.InvariantCulture, out time))
                        {

                        }
                    }
                    else if (s.StartsWith($"{FPS_TAG}:", StringComparison.Ordinal))
                    {

                    }
                }

                while ((line = sr.ReadLine()) != null)
                {
                    linesRead++;

                    if (line.StartsWith(prefix, StringComparison.Ordinal))
                    {
                        return decimal.TryParse(
                            line.AsSpan(prefix.Length),
                            NumberStyles.Number,
                            CultureInfo.InvariantCulture,
                            out fps);
                    }

                    // Optional: stop early if you only ever write this in the header.
                    if (linesRead >= 8)
                        break;
                }
            }


            return false;
        }
    }
}
